[window]
padding = { x = 10, y = 10 }
decorations = "None"

[font]
normal = { family = "monospace", style = "Regular" }
size = 10

[colors]

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.normal]
black   = "#665c54"
red     = "#cc241d"
green   = "#b8bb26" #"#98971a"
yellow  = "#d79921"
blue    = "#83a598" #"#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#ebdbb2"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#fbf1c7"

